// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: craft.proto

package craft

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Req string `protobuf:"bytes,1,opt,name=Req,proto3" json:"Req,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_craft_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_craft_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_craft_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetReq() string {
	if x != nil {
		return x.Req
	}
	return ""
}

type Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rep string `protobuf:"bytes,1,opt,name=Rep,proto3" json:"Rep,omitempty"`
}

func (x *Reply) Reset() {
	*x = Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_craft_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_craft_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_craft_proto_rawDescGZIP(), []int{1}
}

func (x *Reply) GetRep() string {
	if x != nil {
		return x.Rep
	}
	return ""
}

var File_craft_proto protoreflect.FileDescriptor

var file_craft_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x63, 0x72, 0x61, 0x66, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x63,
	0x72, 0x61, 0x66, 0x74, 0x22, 0x1b, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x52, 0x65,
	0x71, 0x22, 0x19, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x65,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x52, 0x65, 0x70, 0x32, 0x38, 0x0a, 0x0a,
	0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x2a, 0x0a, 0x0a, 0x47, 0x65,
	0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x0e, 0x2e, 0x63, 0x72, 0x61, 0x66, 0x74,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x63, 0x72, 0x61, 0x66, 0x74,
	0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_craft_proto_rawDescOnce sync.Once
	file_craft_proto_rawDescData = file_craft_proto_rawDesc
)

func file_craft_proto_rawDescGZIP() []byte {
	file_craft_proto_rawDescOnce.Do(func() {
		file_craft_proto_rawDescData = protoimpl.X.CompressGZIP(file_craft_proto_rawDescData)
	})
	return file_craft_proto_rawDescData
}

var file_craft_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_craft_proto_goTypes = []interface{}{
	(*Request)(nil), // 0: craft.Request
	(*Reply)(nil),   // 1: craft.Reply
}
var file_craft_proto_depIdxs = []int32{
	0, // 0: craft.GetChannel.GetChannel:input_type -> craft.Request
	1, // 1: craft.GetChannel.GetChannel:output_type -> craft.Reply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_craft_proto_init() }
func file_craft_proto_init() {
	if File_craft_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_craft_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_craft_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_craft_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_craft_proto_goTypes,
		DependencyIndexes: file_craft_proto_depIdxs,
		MessageInfos:      file_craft_proto_msgTypes,
	}.Build()
	File_craft_proto = out.File
	file_craft_proto_rawDesc = nil
	file_craft_proto_goTypes = nil
	file_craft_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GetChannelClient is the client API for GetChannel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GetChannelClient interface {
	GetChannel(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
}

type getChannelClient struct {
	cc grpc.ClientConnInterface
}

func NewGetChannelClient(cc grpc.ClientConnInterface) GetChannelClient {
	return &getChannelClient{cc}
}

func (c *getChannelClient) GetChannel(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/craft.GetChannel/GetChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetChannelServer is the server API for GetChannel service.
type GetChannelServer interface {
	GetChannel(context.Context, *Request) (*Reply, error)
}

// UnimplementedGetChannelServer can be embedded to have forward compatible implementations.
type UnimplementedGetChannelServer struct {
}

func (*UnimplementedGetChannelServer) GetChannel(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChannel not implemented")
}

func RegisterGetChannelServer(s *grpc.Server, srv GetChannelServer) {
	s.RegisterService(&_GetChannel_serviceDesc, srv)
}

func _GetChannel_GetChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetChannelServer).GetChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/craft.GetChannel/GetChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetChannelServer).GetChannel(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _GetChannel_serviceDesc = grpc.ServiceDesc{
	ServiceName: "craft.GetChannel",
	HandlerType: (*GetChannelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetChannel",
			Handler:    _GetChannel_GetChannel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "craft.proto",
}
